# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YQNyOR2tk6NTaRMd8fXiOV5iVvhnKn23
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import random

# 1. Define list of emotions
emociones = [
    "Alegría", "Tristeza", "Enojo", "Miedo", "Justicia",
    "Nostálgia", "Romance", "Intriga", "Ternura"
]

# 2. Load the movie data
# Make sure 'pensamiento (2).xlsx' has been uploaded
peliculas = pd.read_excel('pensamiento (2).xlsx')

# 3. Get user's emotional choice and create movie list
print("¿Cómo te sientes hoy?")
print("Elige una emoción:")
for i, emo in enumerate(emociones, start=1):
    print(f"{i}. {emo}")

opcion = int(input("Escribe el número de tu emoción: "))
emocion_seleccionada = emociones[opcion - 1]
print(f"\nElegiste: {emocion_seleccionada}")

lista_peliculas = peliculas[peliculas['EMOCIÓN'] == emocion_seleccionada]['PELÍCULAS'].tolist()
random.shuffle(lista_peliculas)

# 4. Function to show a batch of recommendations and remove them from the list
def mostrar_y_consumir_recomendaciones(lista, num_to_show=3):
    if not lista:
        return []
    recomendadas = lista[:num_to_show]
    del lista[:num_to_show] # Remove displayed movies from the list
    return recomendadas

# 5. Interactive loop for recommendations
print("\nMuy bien, tienes estas recomendaciones de películas para ti:")

while True:
    if not lista_peliculas:
        print("Listo, esas han sido todas las recomendaciones ❤️")
        break

    recomendadas = mostrar_y_consumir_recomendaciones(lista_peliculas)

    if not recomendadas:
        print("No hay más películas para recomendar con esta emoción.")
        break

    for peli in recomendadas:
        print("•", peli)

    if not lista_peliculas:
        print("Listo, esas han sido todas las recomendaciones ❤️")
        break

    respuesta = input("\n¿Quieres otras recomendaciones? (si/no): ").lower()
    if respuesta == "no":
        print("\nMe alegra que hayas encontrado tu película ideal. Mucha suerte 🍿✨")
        break
    elif respuesta == "si":
        print("\nAquí tienes más:")
    else:
        print("Respuesta no válida. Saliendo de las recomendaciones.")
        break